name       : python-pyacoustid
version    : 1.2.2
release    : 1
source     :
    - https://files.pythonhosted.org/packages/source/p/pyacoustid/pyacoustid-1.2.2.tar.gz : c279d9c30a7f481f1420fc37db65833b5f9816cd364dc2acaa93a11c482d4141
homepage   : https://github.com/beetbox/pyacoustid
license    : MIT
component  : programming.python
summary    : Python bindings for Chromaprint acoustic fingerprinting and the Acoustid Web service
description: |
    Chromaprint and its associated Acoustid Web service make up a high-quality, open-source acoustic fingerprinting system. This package provides Python bindings for both the fingerprinting algorithm library, which is written in C but portable, and the Web service, which provides fingerprint lookups.
builddeps  :
    - python-build
    - python-installer
rundeps    :
    - python-audioread
    - python-requests
build      : |
    %python3_setup
install    : |
    %python3_install
